openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/steedos/oauth0/1.0.0
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/steedos/auth0/1.0.0
info:
  description: Partial of Auth0 for login
  version: "1.0.0"
  title: Auth0 Server API
  contact:
    email: zhuangjianguo@hotoa.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: user
    description: Logged in users
  - name: guest
    description: Guests before login
paths:
  /usernamepassword/login:
    post:
      tags:
        - guest
      summary: 
      operationId: login
      description: |
        Login to clientID(app) by username and password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                client_id:
                  type: string
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: object
                properties:
                  id: 
                    type: string
                  username:
                    type: string
                  email:
                    type: string
                  email_verified:
                    type: string
                  
        '400':
          description: bad input parameter
components:
  schemas:
    User:
      type: object
      required:
        - id
        - email
        - password
      properties:
        id:
          type: string
        name:
          type: string
        username:
          type: string
        password:
          type: string
        email: 
          type: string
        email_verified:
          type: boolean