datasources:
  default:
    connection: 
      url: ${MONGO_URL}
public:
  cfs:
    store: "local"
    local: 
      folder: "./storage"
  templateSpaceId: template
plugins:
  - "@steedos/app-crm"
  - "@steedos/steedos-plugin-workflow"
enable_holidays: true