"$schema": http://json-schema.org/draft-04/schema#
id: steedosAppSchema
type: object
title: Steedos App
description: The properties and shape of the Steedos App
properties:
  _id:
    type: string
    title: 主键
  name:
    type: string
    title: 名称
  url:
    type: string
    title: 链接
  icon:
    type: string
    title: 图标
  icon_slds:
    type: string
    title: 图标
  description:
    type: string
    title: 描述
  objects:
    type: array
    title: 对象
    items:
      type: string
  visible:
    type: boolean
    title: 是否可见
  sort:
    type: number
    title: 排序
  is_creator:
    type: boolean
    title: creator应用
  unique_id:
    type: string
    title:
  version:
    type: string
    title:
  from:
    type: string
    title:
    pattern: 0|1|2
  auth_name:
    type: string
    title: 验证域名
  secret:
    type: string
    title: API 密钥
    maxLength: 16
    minLength: 16
  mobile:
    type: boolean
    title: 在移动应用中显示
  is_use_ie:
    type: boolean
    title: 使用IE打开(需使用Steedos桌面客户端)
  is_use_iframe:
    type: boolean
    title: 使用iframe打开
  is_new_window:
    type: boolean
    title: 新窗口打开
  on_click:
    type: string
    title: 链接脚本
  members:
    type: object
    title: 授权对象
    properties:
      users:
        type: array
        title: 授权人员
        items:
          type: string
      type: array
      title: 授权部门
      items:
        type: string
    additionalProperties: false
additionalProperties: false
required:
  - _id
  - name
